config/routes.rb
Rails.application.routes.draw do
  
  get 'admin/invites', to: 'invites#index'
  resources :invites, except: :index
  
  get 'admin/comments', to: 'comments#index' 
  resources :comments, except: :index

  resources :votes
  

   root 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	validates :name, presence: true, length: {maximum: 30}
	validates :message, presence: true, length: {maximum: 255}
	
end

app/models/invite.rb
class Invite < ActiveRecord::Base


	
	validates :name, presence: true, length: {maximum: 30}
	validates :phone, presence: true, length: {maximum: 30}
	validates :address, presence: true, length: {maximum: 60}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}, :allow_blank => true
	
	


end

app/models/vote.rb
class Vote < ActiveRecord::Base
	validates :ip, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]

	def new
	end

	
	def create
		@comment = Comment.new(comment_params)
		@comment.ip = request.remote_ip
		#
		if @comment.save
			respond_to do |format|
				format.html 
				format.js	
			end	
			
		end
			
	end
		
	
	def index
		@comments = Comment.all
	end	

	def destroy
		
  	@comment.destroy
  	respond_to do |format|
  		format.html { redirect_to admin_comments_path, notice: 'comment was successfully destroyed.' }
  		format.json { head :no_content }
  	end
  end



	private
		def comment_params
			params.require(:comment).permit(:name, :message, :subject)
		end

		def set_comment
			@comment = Comment.find(params[:id])
		end	
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]
  # GET /invites
  # GET /invites.json
  def index
    @invites_taipei = Invite.where(location: '0')
    @invites_taitung = Invite.where(location: '1')
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)
    @invite.ip = request.remote_ip
  
    respond_to do |format|
      if @invite.save
      
        format.html #{ redirect_to @invite, notice: 'Invite was successfully created.' }
        format.js #{ render :show, status: :created, location: @invite }
      else
        #format.html { render :new }
        format.js #{ render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to admin_invites_path, notice: 'Invite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:name, :email, :phone, :address, :company, :location, :isVeg, :zipcode)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		# get public messages
		@comments = Comment.where(subject: 0).order('created_at DESC').first(10)
	end

	
		
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def new
		@vote = Vote.new
		@nicks = distinct_count_query(1)
		@maggies = distinct_count_query(2)
	end
	
	def create
		@vote = Vote.new(vote_params)
    @vote.ip = request.remote_ip
  
    respond_to do |format|
      if @vote.save

      	@nicks = distinct_count_query(1)
				@maggies = distinct_count_query(2)

      
        #format.html #{ redirect_to @invite, notice: 'Invite was successfully created.' }
        format.js #{ render location: @nicks,@maggies }
      else
      	@message =" Looks like you've voted before. Thanks for yor support !"
      	@nicks = distinct_count_query(1)
				@maggies = distinct_count_query(2)
        #format.html { render :new }
        format.js #{ render json: @invite.errors, status: :unprocessable_entity }
      end
    end
	end

	def show

	end

	private
		def vote_params
      params.require(:vote).permit(:candidate)
    end

    def distinct_count_query(name)
    	Vote.where(candidate: name).select(:ip).distinct.count
    end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

	def render_subject(subject)
		if subject == 0
			"公開"
		elsif
			subject == 1
			"私下"
		end	
	end	
end

app/helpers/invites_helper.rb
module InvitesHelper

	def render_isVeg(isVeg)
		if isVeg 
			"吃素"
		else isVeg 
			"無"
		end		
	end

	def render_location(location)
		if location == "1"
			"台東"
		elsif location == "0"
			"台北"
		end		
	end	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def right_or_left(index)
		if index%2 == 0
			raw("right")
		else
			raw("left")
		end	
	end

	def render_offset(index)
		if index%2 != 0
			raw("col-md-offset-6")
		
		end	
	end		


end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/create.js.erb
swal("Thank You! <%= @comment.name %> ", "Your message has been created successfully!", "success");
if ( <%= @comment.subject %> == 0){
	$('#comments_area').prepend("<%= escape_javascript(render 'static_pages/message', :comment => @comment, :index => 1)  %>" );

}

<%#= render 'static_pages/message', :comment => @comment, :index => 1 %>
//simple_format 

$('#comment_name').val('');
$('#comment_message').val('');
window.location.hash = '#board';

app/views/comments/index.html.erb
<div style="padding-top:100px;"></div>
<h1>Listing Comments</h1>

<table class="table" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Message</th>
      <th>Subject</th>
      <th>Ip</th>	
      <th></th>	
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.updated_at.to_s(:short) %></td>
        <td><%= simple_format(comment.message) %></td>
        <td><%= render_subject comment.subject %></td>
        <td><%= comment.ip %></td>
        <!--
        <td><%#= link_to 'Show', comment %></td>
        <td><%#= link_to 'Edit', edit_comment_path(comment) %></td>
        -->
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/invites/_form.html.erb
<%= form_for(@invite, :html => {:class => "form-horizontal"} ) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row col-lg-6 col-lg-offset-3">
    <div class="col-xs-12 form-group">
      <%= f.label :name, "姓名", :class => "control-label " %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>

    <div class="col-xs-12 form-group">
      <%= f.label :email, "Email", :class => "control-label" %>`
      <%= f.email_field :email, :class => "form-control" %>
    </div>

    <div class="col-xs-12 form-group">
      <%= f.label :phone, "聯絡電話", :class => "control-label " %>
      <%= f.text_field :phone, :class => "form-control" %>
    </div>
   
    <div class="col-xs-12 form-group">
      <%= f.label :address, "聯絡地址", :class => "control-label " %>
      <%= f.text_field :address, :class => "form-control" %>
    </div>


  </div>    

    
  <div class="row col-lg-6 col-lg-offset-3 col-xs-12">
    <div class="col-md-4 form-group">
        <%= f.label :company, "攜伴人數", :class => "control-label " %>
        <%= f.number_field :company,  :class => "form-control", :style => "width:50%;", :min => "0", :max => "5" %>
    </div>

    <div class="col-md-4 form-group col-xs-12">  
        <%= f.label :location, "場次", :class => "control-label " %>
        <%= f.text_field :location, :style => "width:80%;", :class => "form-control" %>
    </div>

    <div class="col-md-4 form-group col-xs-12">  
        <%= f.label :isVeg, "素食",:class => "control-label " %>
        <%= f.check_box :isVeg, :class => "form-control" %> 

      
    </div>

  </div>

  <div class="row col-lg-6 col-lg-offset-3 col-xs-12">
    
    <hr>

    <p><b> 祝福的話 </b></p>
    <div>
      <div class="">
        <a class="btn btn-success">公開</a>&nbsp;&nbsp;
        <a class="btn btn-warning">Maggie</a>&nbsp;&nbsp;
        <a class="btn btn-info">Nick</a>&nbsp;&nbsp;
        <a class="btn btn-default">Nick & Maggie</a>
       </div>
    
    
      <br>
      <textarea style="width=100%;" rows="10" class="form-control">
        Hi, 
      </textarea>
      <br>
    </div>  

  </div> 
 

<div class="row">
  <div class="col-xs-12">
  <%= f.submit "送出資料", :class => "btn-primary btn center-block" %>
  </div>
</div> 
 


<% end %>

app/views/invites/create.js.erb
if ( <%= @invite.errors.present? %>) {
	$('#invite_email').parent().addClass('has-error');
	$('#invite_email').focus();
		
} else {
	$('#invite_email').parent().removeClass('has-error');

	swal("Thank You! <%= @invite.name %> ", "We've received your post!", "success");

	<%#= render 'static_pages/message', :comment => @comment, :index => 1 %>
	//simple_format 

	$('#invite_name').val('');
	$('#invite_email').val('');
	$('#invite_phone').val('');
	$('#invite_address').val('');
	$('#invite_company').val(0);

	$('#invite_isVeg').attr('checked', false);

}

app/views/invites/edit.html.erb
<h1>Editing invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<div class="container">

  <div style="padding-top:100px;"></div>
  <h1><span class="text-info">TAITUNG</span> Listing invites</h1>

  <table class="table table-striped" >
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Zipcode</th>
        <th>Address</th>
        <th>Company</th>
        <th>Location</th>
        <th>Isveg</th>
        <th>Time</th>
        <th>Ip</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @invites_taitung.each_with_index do |invite, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= invite.name %></td>
          <td><%= invite.email %></td>
          <td><%= invite.phone %></td>
          <td><%= invite.zipcode %></td>
          <td><%= invite.address %></td>
          <td><%= invite.company %></td>
          <td><%= render_location invite.location %></td>
          <td><%= render_isVeg invite.isVeg %></td>
          <td><%= invite.updated_at.to_s(:short) %></td>
          <td><%= invite.ip %></td>
          <!--
          <td><%#= link_to 'Show', invite %></td>
          <td><%#= link_to 'Edit', edit_invite_path(invite) %></td>
          -->
          <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>



  <div style="padding-top:100px;"></div>
  <h1><span class="text-success">TAIPEI</span> Listing invites</h1>

  <table class="table table-striped" >
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Zipcode</th>
        <th>Address</th>
        <th>Company</th>
        <th>Location</th>
        <th>Isveg</th>
        <th>Time</th>
        <th>Ip</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @invites_taipei.each_with_index do |invite, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= invite.name %></td>
          <td><%= invite.email %></td>
          <td><%= invite.phone %></td>
          <td><%= invite.zipcode %></td>
          <td><%= invite.address %></td>
          <td><%= invite.company %></td>
          <td><%= render_location invite.location %></td>
          <td><%= render_isVeg invite.isVeg %></td>
          <td><%= invite.updated_at.to_s(:short) %></td>
          <td><%= invite.ip %></td>
          <!--
          <td><%#= link_to 'Show', invite %></td>
          <td><%#= link_to 'Edit', edit_invite_path(invite) %></td>
          -->
          <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>
<%#= link_to 'New Invite', new_invite_path %>

app/views/invites/new.html.erb
	<h1>R S V P</h1>

	<%= render 'form' %>

	<%#= link_to 'Back', invites_path %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invite.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @invite.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @invite.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @invite.address %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invite.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @invite.location %>
</p>

<p>
  <strong>Isveg:</strong>
  <%= @invite.isVeg %>
</p>

<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>

app/views/layouts/_footer.html.erb
<footer>
<hr>
	<div class="row">
        <div class="col-lg-12">
        	
        	Copyright &copy; nickNmaggie.us 2014
        </div>
    </div>

</footer>

app/views/layouts/_header.html.erb
<!--
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">History</a></li>
       
        <li><a href="#contact">Information</a></li>
        <li><a href="#contact">RSVP</a></li>
      </ul>

    </div> 
  </div>
</div>
-->

 <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand page-scroll" href="<%= root_path %>" data-no-turbolink="true">Nick & Maggie</a> -->
                <a name="page-top" class="navbar-brand page-scroll" href="<%= root_path %>">Nick & Maggie</a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="myScrollspy">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= root_path%>#profile">關於我們</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= root_path%>#photos">照片們</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= root_path%>#invite">出席宴會</a>          
                        
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= root_path%>#location">宴會資訊</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= root_path%>#comment">祝福的話</a>
                    </li>
                    <li>
                        <a class="page-scroll" href=" <%= new_vote_path %>" data-no-turbolink="true" >影片對抗</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html prefix="og: http://ogp.me/ns#">

<head>

  <title>Wedding | Nick & Maggie | 12.27.2014 | 01.17.2015 </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  	<script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="<%= asset_path('favicon.ico')%>" />
  <meta name="fb:app_id" content="1503510986585092"/>
  <meta property="fb:admins" content="758238745" />
  <meta name="og:site_name" content="nickNmaggie"/>
  <% if content_for? :for_head %>
    <%= yield :for_head %>
  <% end %>   

  <script type="text/javascript">
  	jQuery(function(){
     	jQuery(".player").mb_YTPlayer();

    });
  </script>

</head>


<body data-spy="scroll" data-target="#myScrollspy" id="page-top">
  <div id="fb-root"></div>

<script>
/*
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1503510986585092',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  */
</script>
<%= render 'layouts/header' %> 


	<%= yield %>


<%= render 'layouts/footer' %>

</body>
</html>

<script>



  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56031113-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/_message.html.erb
<div class="row <%= render_offset index%> ">
  <div class="popover <%= right_or_left index%> in " style="display: block;">
    <div class="arrow"></div>
    <div class="popover-title"><h3><%= comment.name %> 說：</h3></div>
    <div class="popover-content">
       <h4 class="lead"><%= simple_format comment.message %></h4>
      <div class="pull-right"><%= time_ago_in_words(comment.created_at) %> ago.</div>
    </div>
  </div>
</div>  

app/views/static_pages/_section_comment.html.erb
<a name="comment"></a>
<div class="title text-center" id="comment">
  <%= image_tag("boy.png", :alt => "rss feed", :class => "img-circle img-responsive img-center" , :width => "200") %><h1> 祝福的話 </h1>
</div>

<section class="content-section">
  <div class="container">
    <%= form_for(Comment.new, :html => {:class => "form-horizontal"}, remote: true) do |f| %>
      <div class="form-group">
        <div class="col-xs-12 ">
          <%= fa_icon "user" %> &nbsp;<%= f.label :name, "姓名", :class => "control-label  " %>
        </div>
     
        <div class="col-xs-12 col-sm-4">
          <%= f.text_field :name, :class => "form-control ", :id => "comment_name" %>
        </div>
      </div>   
    



      <div class="row">
        
        <!--<button type="button" class="btn btn-success active" id="public_btn">公開</button>&nbsp; 
        -->
        <div class="col-md-6">
          <label class="control-label">留言給 &nbsp;&nbsp;&nbsp;&nbsp;</label>
          <div class="btn-group form-control no-border" data-toggle="buttons" style="padding-left:0px;">
            <button class="btn btn-default" id="both_btn" >Nick & Maggie</button> 
            <a class="btn btn-warning" id="maggie_btn">Maggie</a>
            <a class="btn btn-info"id="nick_btn">Nick</a>
          </div>  
        </div>

        <div class="col-md-6"> 

          <label class="control-label">方式 &nbsp;(公開會發表在網站 私下留言就有 Maggie 或 Nick 會看到)</label>

          <div class="btn-group form-control no-border" data-toggle="buttons" style="padding-left:0px;">
            <label id="public_label" class="btn btn-success active">
              <input name="comment[subject]" type="radio" value="0" checked="checked" />
              <span>公開</span>
            </label>

            <label id="private_label" class="btn btn-success ">
              <input name="comment[subject]" type="radio" value="1"/>
              <span>私下  </span>
            </label>
            
          </div>
        
        


        </div>

      </div>  
        
      <br>
      <!--
      <textarea style="width=100%;" rows="10" class="form-control" name="comment[message]"></textarea>-->
      <%= f.text_area :message, :value => "Hi, Maggie & Nick\n", :rows => "10", :class => "form-control", :style => "width:100%;" %>
      <br>

  <!--
      <a class="btn-link btn"><%#= fa_icon "trash" %> &nbsp;取消這則留言</a>

      <div class="row" >
        <div class="col-xs-12" style="margin-top:0px;">
          <button class="btn btn-success center-block"><%#= fa_icon "pencil" %> &nbsp;新增一則祝福的話</button>
        </div>
      </div> 
  -->


      <div class="row" >
        <div class="col-xs-12" style="margin-top:0px;">
          <button type="button" id="comment_btn" class="btn btn-lg btn-primary center-block"><%= fa_icon "pencil" %> &nbsp;送出這則祝福的話</button>
        </div>
      </div> 
    <% end %>  

    <br>

    <div class="title text-center" id="board">
      <%= image_tag("girl.png", :alt => "rss feed", :class => "img-circle img-responsive img-center" , :width => "200") %><h1> 大家的祝福 </h1>
    </div>


    <div id="comments_area" class="bs-example-popover ">

      <% @comments.each.with_index do |comment, index| %>

        <%= render 'message' ,:comment => comment,:index => index %>
      <% end %>    
    </div>

  </div>    
</section>

<script type="text/javascript">
  //$('#public_btn').click(function(){
  $( "#both_btn" ).on( "click", function(e) {  

    $('#comment_message').val('Hi, Maggie & Nick\n');
    $('#comment_message').focus();
    $('#both_btn').parent().addClass('active');

    $('#nick_btn').removeClass('active');
    $('#maggie_btn').removeClass('active');


  });
  $('#maggie_btn').click(function(){
    $('#comment_message').val('Hi, Maggie\n');
    $('#comment_message').focus();
    $('#maggie_btn').parent().addClass('active');
    $('#nick_btn').removeClass('active');
    $('#both_btn').removeClass('active');
  });

  $('#nick_btn').click(function(){
    $('#comment_message').val('Hi, Nick\n');
    $('#comment_message').focus();
    $('#nick_btn').parent().addClass('active');
    $('#maggie_btn').removeClass('active');
    $('#both_btn').removeClass('active');
  });


  $( "#comment_btn" ).on( "click", function(e) { 
    e.preventDefault();
   
    if (validation_comment()){
      $('#new_comment').submit();
    }
  });

  function validation_comment(){

    if ($('#comment_name').val() == "") {
      $('#comment_name').parent().addClass('has-error');
      $('#comment_name').focus();
      return false;
    }else {
      $('#comment_name').parent().removeClass('has-error');
    }

    if ($('#comment_message').val() == "") {
      $('#comment_message').parent().addClass('has-error');
      $('#comment_message').focus();
      return false;
    }else {
      $('#comment_message').parent().removeClass('has-error');
    }    

    return true;
  }



</script>


 

app/views/static_pages/_section_gallery.html.erb
<a name="photos"></a>
<div class="title text-center" id="photos">
  <%= image_tag("frog.png", :alt => "rss feed", :class => "img-circle img-responsive img-center" , :width => "200") %><h1> 照片們 </h1>
</div>
<div class="container">

  <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
    <!-- Carousel indicators -->
      <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
          <li data-target="#myCarousel" data-slide-to="4"></li>
          <li data-target="#myCarousel" data-slide-to="5"></li>
          
      </ol>   
     <!-- Carousel items -->
      <div class="carousel-inner">
          <div class="active item">
            
            <%= image_tag("1046274861_x.jpg", :width => "1200") %>
          </div>
          <div class="item">
            <%= image_tag("1049916419_x.jpg", :width => "1200") %>
          </div>
          <div class="item">
            <%= image_tag("1049920577_x.jpg", :width => "1200") %>
          </div>
          <div class="item">
             <%= image_tag("1049923568_x.jpg", :width => "1200") %>
          </div>
          <div class="item">
             <%= image_tag("1049924980_x.jpg", :width => "1200") %>
          </div>
          <div class="item">
             <%= image_tag("1049920586_x.jpg", :width => "1200") %>
          </div>
      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
  </div>
  <br>
  <div 
    style="margin-top:20px;"
    class="fb-like"
    data-share="true"
    data-width="450"
    data-show-faces="true">
  </div>
</div>  

app/views/votes/create.js.erb
if (<%= @message.present? %>){
	sweetAlert("<%= raw @message %>");

} else {
	sweetAlert("Thank you for the vote!");
}

//alert('Thank You');
$('#count_nicks').html("<%= @nicks %>");
$('#count_maggies').html("<%= @maggies %>");